// Generated by Wrangler on Mon Jul 08 2024 11:46:09 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	COOKIE_SESSION_SECRET: string;
	DB: D1Database;
}
